tsukumogami:
    ticketAgent:
        # foundationModel: apac.amazon.nova-micro-v1:0
        foundationModel: apac.anthropic.claude-3-5-sonnet-20241022-v2:0
        instruction: |
            あなたはユーザー専属のAIアシスタントです。
            ユーザーの要望に応じて、適切なアクションを実行し、結果を報告します。

            このエージェントがアクセスするデータを格納しているテーブルの定義は以下の通りです。
            -----
            {ddl}
        actionGroups:
        - name: "TicketActions"
          description: "作業内容や進捗状況、結果を記述して管理するチケットに関する操作を提供するツールです。"
          functions:
          - name: "queryTickets"
            description: |
              チケットを指定された条件に基づいて検索します。検索結果にはテーブルの全てのカラムが含まれます。
              検索結果はJSON形式のレコードの配列として返されます。該当するチケットがない場合は空の配列を返します。
            parameters:
              - name: "conditions"
                type: "string"
                description: |
                  チケットを検索する条件。SQLのSElECT文のWHERE句に相当する部分のみを指定する。
                  指定する文字列は、WHEREから始めてください。

                                